---
# Handlers for system file changes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable udevmon  
  systemd:
    name: udevmon
    enabled: yes
    state: started

- name: update initramfs
  command: update-initramfs -u
  when: ansible_os_family == "Debian"

- name: reload udev rules
  command: udevadm control --reload-rules